on:
  push:
    branches: main

name: Render and Publish using quarto

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        
      - name: Install python packages
        run: python3 -m pip install -r requirements.txt
      
      - name: Set up directories
        run:
          mkdir data
          mkdir downloads

      - uses: dsaltares/fetch-gh-release-asset@master
        with:
          repo: 'tydenet/ipni-types'
          version: 'latest'
          file: " ipni-types-data.zip "
          target: 'downloads/ipni-types-data.zip'
          token: ${{ secrets.PAT }}

      - name: Unzip contents of downloaded ipni-types-data.zip
        run: unzip -j -d data downloads/ipni-types-data.zip

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      
      # add software dependencies here

      - name: Publish to GitHub Pages (and render)
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # this secret is always available for github actions
